# Generated by Django 3.0 on 2021-01-29 14:32

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('illumination', models.BooleanField()),
                ('ill_cross1', models.BooleanField()),
                ('ill_cross2', models.BooleanField()),
                ('ill_cross3', models.BooleanField()),
                ('ill_cross4', models.BooleanField()),
                ('color_cross1', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
                ('color_cross2', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
                ('color_cross3', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
                ('color_cross4', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
                ('rotation', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Image')),
            ],
        ),
    ]
